### PR TITLE
Add all-in-one wrappers.

### LINKED ISSUE #81: Use tqdm progress bars in the run experiment functions
Many of these take a very long time, so it would be nice to get some feedback on how much time is left.

### LINKED ISSUE #178: Add high-level wrapper with common defaults
Add a convenient all-in-one method that abridges the generate->acquire->analyze separation.

### PR DESCRIPTION
**Pull request by kylegulshen**
This has a few API / signature changes. The main contribution is to add a `do_x` wrapper that does all three stages of the experiment together with default parameters. The args list and order is standardized for all of these routines, and the args for similar functions was made to match this. 

closes #178
closes #81

### CODE REVIEW

**Comment by kylegulshen** [comment]
Waiting for #181 to be merged before fixing the notebooks and finalizing things.

**Comment by kylegulshen** [comment]
closes #178

**Comment by kylegulshen** [comment]
@stylewarning

**Comment by stylewarning** [comment]
@kylegulshen Fix the tests.

**Comment by stylewarning** [comment]
Also, can you rebase this?

**Comment by stylewarning** [comment]
Waiting for tests, then I'll merge if they pass.

**Pull request merged**
