### PR TITLE
Fix new dfe

### PR DESCRIPTION
**Pull request by msohaibalam**
WIP [Work in Progress]: Complete the new way of doing DFE by using symmetrization + calibration from pyquil:operator_estimation's `measure_observables`

### CODE REVIEW

**Comment by blakejohnson** [comment]
@marcusps @msohaibalam do we need to hand this work off to someone else to get it over the finish line?

**Comment by marcusps** [comment]
@msohaibalam is moving on to another project, so I am taking over. I was gated by the PR for `measure_observables` in PyQuil, which is now merged, so I don't expect problems, @blakejohnson

**Comment by blakejohnson** [comment]
We should close this, as it is has been superseded by @marcusps's PR.

**Comment by msohaibalam** [comment]
Closed and deleted branch.

**Pull request closed without merging**
