### PR TITLE
Rename notebooks

### PR DESCRIPTION
**Pull request by joshcombes**
This makes the example notebook names consistent with the modules. When there was no title I added a title to the notebook.

There is a larger discussion surrounding getting all notebooks to the same standard of pedagogy.

### CODE REVIEW

**Comment by mpharrigan** [comment]
Can you remove the changes to the `metadata` part? You can use some git foo (perhaps `git add -p`) or use this snippet https://gist.github.com/mpharrigan/14f3c93be5520d139ea265ad95249663

we want to reduce git-diff-noise from jupyter's computer-specific metadata

**Comment by mpharrigan** [comment]
but it leaves all the 
```json
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
```

which will be different on each person's computer

**Comment by joshcombes** [comment]
Hmm that is annoying.

**Comment by joshcombes** [comment]
I think it is done.

**Comment by mpharrigan** [comment]
Thanks!

**Pull request merged**
